import SearchPage from "@/app/Components/Searchpage";


export async function generateMetadata({ params }: { params: { slug: string } }) {
  const decodedSlug = decodeURIComponent(params.slug);

  return {
    title: `${decodedSlug}`, // Dynamically set title
    description: `Generated by create next app`, // Dynamically set description
  };
}
export default function Page({ params }: { params: { slug: string } }) { 
  const decodedSlug = decodeURIComponent(params.slug);
    return (
     <>
     <SearchPage slug={decodedSlug} />
     </>
    )
  }
