
import SectionCard from "../cards";


export async function generateMetadata({ params }: { params: { slug: string } }) {
  const decodedSlug = decodeURIComponent(params.slug);

  return {
    title: `${decodedSlug}`, // Dynamically set title
    description: `Generated by create next app`, // Dynamically set description
  };
}
export default function Page({ params }: { params: { slug: string } }) { 
  const decodedSlug = decodeURIComponent(params.slug);

    return (
        <>
        <div className=" lg:mx-32 md:mx-5  mb-8 bg-white dark:bg-slate-950">
          <SectionCard   category={decodedSlug}  />
        </div>
      </>
    )
  }
